#!/usr/bin/env bash
# Post a Claude code review to the open PR for the current branch.
# Skips silently if no PR is open or if anything fails — never blocks the commit.

PR_NUMBER=$(gh pr view --json number --jq '.number' 2>/dev/null) || true
[ -z "$PR_NUMBER" ] && exit 0

DIFF=$(git diff --cached)
[ -z "$DIFF" ] && exit 0

REVIEW=$(printf 'Review the following staged git diff and provide a concise code review. Focus on bugs, logic errors, security issues, and significant code quality concerns. If the changes look good, say so briefly. Format your response as markdown.\n\n```diff\n%s\n```' "$DIFF" | claude -p 2>/dev/null) || true

[ -z "$REVIEW" ] && exit 0

gh pr comment "$PR_NUMBER" --body "$(printf '## Claude Code Review\n\n%s\n\n---\n*Generated by Claude Code at commit time*' "$REVIEW")"
